application: uberbattleship
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- admin_redirect: on
- appstats: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /.*
  script: app.app

libraries:
- name: webapp2
  version: "latest"
